# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/playtest/dev/mcc-unnamed-sdvx-clone

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/playtest/dev/mcc-unnamed-sdvx-clone

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/playtest/dev/mcc-unnamed-sdvx-clone/CMakeFiles /home/playtest/dev/mcc-unnamed-sdvx-clone//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/playtest/dev/mcc-unnamed-sdvx-clone/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nanovg

# Build rule for target.
nanovg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanovg
.PHONY : nanovg

# fast build rule for target.
nanovg/fast:
	$(MAKE) $(MAKESILENT) -f third_party/CMakeFiles/nanovg.dir/build.make third_party/CMakeFiles/nanovg.dir/build
.PHONY : nanovg/fast

#=============================================================================
# Target rules for targets named sqlite3

# Build rule for target.
sqlite3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sqlite3
.PHONY : sqlite3

# fast build rule for target.
sqlite3/fast:
	$(MAKE) $(MAKESILENT) -f third_party/CMakeFiles/sqlite3.dir/build.make third_party/CMakeFiles/sqlite3.dir/build
.PHONY : sqlite3/fast

#=============================================================================
# Target rules for targets named minimp3

# Build rule for target.
minimp3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 minimp3
.PHONY : minimp3

# fast build rule for target.
minimp3/fast:
	$(MAKE) $(MAKESILENT) -f third_party/CMakeFiles/minimp3.dir/build.make third_party/CMakeFiles/minimp3.dir/build
.PHONY : minimp3/fast

#=============================================================================
# Target rules for targets named soundtouch

# Build rule for target.
soundtouch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 soundtouch
.PHONY : soundtouch

# fast build rule for target.
soundtouch/fast:
	$(MAKE) $(MAKESILENT) -f third_party/CMakeFiles/soundtouch.dir/build.make third_party/CMakeFiles/soundtouch.dir/build
.PHONY : soundtouch/fast

#=============================================================================
# Target rules for targets named GLEW

# Build rule for target.
GLEW: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GLEW
.PHONY : GLEW

# fast build rule for target.
GLEW/fast:
	$(MAKE) $(MAKESILENT) -f third_party/CMakeFiles/GLEW.dir/build.make third_party/CMakeFiles/GLEW.dir/build
.PHONY : GLEW/fast

#=============================================================================
# Target rules for targets named lua

# Build rule for target.
lua: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lua
.PHONY : lua

# fast build rule for target.
lua/fast:
	$(MAKE) $(MAKESILENT) -f third_party/lua-5.3.5/CMakeFiles/lua.dir/build.make third_party/lua-5.3.5/CMakeFiles/lua.dir/build
.PHONY : lua/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zlib-build/CMakeFiles/zlib.dir/build.make _deps/zlib-build/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/CMakeFiles/uninstall.dir/build.make _deps/curl-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named libcurl

# Build rule for target.
libcurl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libcurl
.PHONY : libcurl

# fast build rule for target.
libcurl/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/lib/CMakeFiles/libcurl.dir/build.make _deps/curl-build/lib/CMakeFiles/libcurl.dir/build
.PHONY : libcurl/fast

#=============================================================================
# Target rules for targets named cpr

# Build rule for target.
cpr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpr
.PHONY : cpr

# fast build rule for target.
cpr/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cpr/cpr/CMakeFiles/cpr.dir/build.make third_party/cpr/cpr/CMakeFiles/cpr.dir/build
.PHONY : cpr/fast

#=============================================================================
# Target rules for targets named discord-rpc

# Build rule for target.
discord-rpc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 discord-rpc
.PHONY : discord-rpc

# fast build rule for target.
discord-rpc/fast:
	$(MAKE) $(MAKESILENT) -f third_party/discord-rpc/src/CMakeFiles/discord-rpc.dir/build.make third_party/discord-rpc/src/CMakeFiles/discord-rpc.dir/build
.PHONY : discord-rpc/fast

#=============================================================================
# Target rules for targets named Shared

# Build rule for target.
Shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Shared
.PHONY : Shared

# fast build rule for target.
Shared/fast:
	$(MAKE) $(MAKESILENT) -f Shared/CMakeFiles/Shared.dir/build.make Shared/CMakeFiles/Shared.dir/build
.PHONY : Shared/fast

#=============================================================================
# Target rules for targets named Graphics

# Build rule for target.
Graphics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Graphics
.PHONY : Graphics

# fast build rule for target.
Graphics/fast:
	$(MAKE) $(MAKESILENT) -f Graphics/CMakeFiles/Graphics.dir/build.make Graphics/CMakeFiles/Graphics.dir/build
.PHONY : Graphics/fast

#=============================================================================
# Target rules for targets named usc-game

# Build rule for target.
usc-game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 usc-game
.PHONY : usc-game

# fast build rule for target.
usc-game/fast:
	$(MAKE) $(MAKESILENT) -f Main/CMakeFiles/usc-game.dir/build.make Main/CMakeFiles/usc-game.dir/build
.PHONY : usc-game/fast

#=============================================================================
# Target rules for targets named Audio

# Build rule for target.
Audio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Audio
.PHONY : Audio

# fast build rule for target.
Audio/fast:
	$(MAKE) $(MAKESILENT) -f Audio/CMakeFiles/Audio.dir/build.make Audio/CMakeFiles/Audio.dir/build
.PHONY : Audio/fast

#=============================================================================
# Target rules for targets named Beatmap

# Build rule for target.
Beatmap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Beatmap
.PHONY : Beatmap

# fast build rule for target.
Beatmap/fast:
	$(MAKE) $(MAKESILENT) -f Beatmap/CMakeFiles/Beatmap.dir/build.make Beatmap/CMakeFiles/Beatmap.dir/build
.PHONY : Beatmap/fast

#=============================================================================
# Target rules for targets named GUI

# Build rule for target.
GUI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GUI
.PHONY : GUI

# fast build rule for target.
GUI/fast:
	$(MAKE) $(MAKESILENT) -f GUI/CMakeFiles/GUI.dir/build.make GUI/CMakeFiles/GUI.dir/build
.PHONY : GUI/fast

#=============================================================================
# Target rules for targets named Tests

# Build rule for target.
Tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tests
.PHONY : Tests

# fast build rule for target.
Tests/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/Tests.dir/build.make Tests/CMakeFiles/Tests.dir/build
.PHONY : Tests/fast

#=============================================================================
# Target rules for targets named Tests.Shared

# Build rule for target.
Tests.Shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tests.Shared
.PHONY : Tests.Shared

# fast build rule for target.
Tests.Shared/fast:
	$(MAKE) $(MAKESILENT) -f Tests.Shared/CMakeFiles/Tests.Shared.dir/build.make Tests.Shared/CMakeFiles/Tests.Shared.dir/build
.PHONY : Tests.Shared/fast

#=============================================================================
# Target rules for targets named Tests.Game

# Build rule for target.
Tests.Game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tests.Game
.PHONY : Tests.Game

# fast build rule for target.
Tests.Game/fast:
	$(MAKE) $(MAKESILENT) -f Tests.Game/CMakeFiles/Tests.Game.dir/build.make Tests.Game/CMakeFiles/Tests.Game.dir/build
.PHONY : Tests.Game/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... Audio"
	@echo "... Beatmap"
	@echo "... GLEW"
	@echo "... GUI"
	@echo "... Graphics"
	@echo "... Shared"
	@echo "... Tests"
	@echo "... Tests.Game"
	@echo "... Tests.Shared"
	@echo "... cpr"
	@echo "... discord-rpc"
	@echo "... libcurl"
	@echo "... lua"
	@echo "... minimp3"
	@echo "... nanovg"
	@echo "... soundtouch"
	@echo "... sqlite3"
	@echo "... usc-game"
	@echo "... zlib"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

